package org.jcmg.hibernate.entities;
// Generated Jun 3, 2015 8:18:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private String cif;
     private User user;
     private String name;
     private String logo;
     private Set groups = new HashSet(0);
     private Set students = new HashSet(0);

    public Company() {
    }

    public Company(String cif) {
        this.cif = cif;
    }
	
    public Company(String cif, User user, String name) {
        this.cif = cif;
        this.user = user;
        this.name = name;
    }
    public Company(String cif, User user, String name, String logo, Set groups, Set students) {
       this.cif = cif;
       this.user = user;
       this.name = name;
       this.logo = logo;
       this.groups = groups;
       this.students = students;
    }
   
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public Set getGroups() {
        return this.groups;
    }
    
    public void setGroups(Set groups) {
        this.groups = groups;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


