package org.jcmg.hibernate.entities;
// Generated May 26, 2015 7:20:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exam generated by hbm2java
 */
public class Exam  implements java.io.Serializable {


     private Integer examId;
     private String code;
     private String description;
     private char proficieny;
     private Set studentTakesExams = new HashSet(0);

    public Exam() {
    }

	
    public Exam(String code, String description, char proficieny) {
        this.code = code;
        this.description = description;
        this.proficieny = proficieny;
    }
    public Exam(String code, String description, char proficieny, Set studentTakesExams) {
       this.code = code;
       this.description = description;
       this.proficieny = proficieny;
       this.studentTakesExams = studentTakesExams;
    }
   
    public Integer getExamId() {
        return this.examId;
    }
    
    public void setExamId(Integer examId) {
        this.examId = examId;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public char getProficieny() {
        return this.proficieny;
    }
    
    public void setProficieny(char proficieny) {
        this.proficieny = proficieny;
    }
    public Set getStudentTakesExams() {
        return this.studentTakesExams;
    }
    
    public void setStudentTakesExams(Set studentTakesExams) {
        this.studentTakesExams = studentTakesExams;
    }




}


