package org.jcmg.hibernate.entities;
// Generated Jun 3, 2015 8:18:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer groupId;
     private Company company;
     private Teacher teacher;
     private String groupCode;
     private int hoursPerWeek;
     private Set students = new HashSet(0);

    public Group() {
    }

	
    public Group(Company company, Teacher teacher, String groupCode, int hoursPerWeek) {
        this.company = company;
        this.teacher = teacher;
        this.groupCode = groupCode;
        this.hoursPerWeek = hoursPerWeek;
    }
    public Group(Company company, Teacher teacher, String groupCode, int hoursPerWeek, Set students) {
       this.company = company;
       this.teacher = teacher;
       this.groupCode = groupCode;
       this.hoursPerWeek = hoursPerWeek;
       this.students = students;
    }
   
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public String getGroupCode() {
        return this.groupCode;
    }
    
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }
    public int getHoursPerWeek() {
        return this.hoursPerWeek;
    }
    
    public void setHoursPerWeek(int hoursPerWeek) {
        this.hoursPerWeek = hoursPerWeek;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


