package org.jcmg.hibernate.entities;
// Generated May 22, 2015 8:17:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private MessageId id;
     private User userByReciever;
     private User userBySender;
     private String title;
     private String body;
     private Date date;
     private Boolean read;

    public Message() {
    }

	
    public Message(MessageId id, User userByReciever, User userBySender, String body) {
        this.id = id;
        this.userByReciever = userByReciever;
        this.userBySender = userBySender;
        this.body = body;
    }
    public Message(MessageId id, User userByReciever, User userBySender, String title, String body, Date date, Boolean read) {
       this.id = id;
       this.userByReciever = userByReciever;
       this.userBySender = userBySender;
       this.title = title;
       this.body = body;
       this.date = date;
       this.read = read;
    }
   
    public MessageId getId() {
        return this.id;
    }
    
    public void setId(MessageId id) {
        this.id = id;
    }
    public User getUserByReciever() {
        return this.userByReciever;
    }
    
    public void setUserByReciever(User userByReciever) {
        this.userByReciever = userByReciever;
    }
    public User getUserBySender() {
        return this.userBySender;
    }
    
    public void setUserBySender(User userBySender) {
        this.userBySender = userBySender;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Boolean getRead() {
        return this.read;
    }
    
    public void setRead(Boolean read) {
        this.read = read;
    }




}


