package org.jcmg.hibernate.entities;
// Generated Jun 3, 2015 8:18:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NonAttendance generated by hbm2java
 */
public class NonAttendance  implements java.io.Serializable {


     private Integer nonAttendanceId;
     private Student student;
     private boolean proof;
     private Date date;

    public NonAttendance() {
    }

    public NonAttendance(Student student, boolean proof, Date date) {
       this.student = student;
       this.proof = proof;
       this.date = date;
    }
   
    public Integer getNonAttendanceId() {
        return this.nonAttendanceId;
    }
    
    public void setNonAttendanceId(Integer nonAttendanceId) {
        this.nonAttendanceId = nonAttendanceId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public boolean isProof() {
        return this.proof;
    }
    
    public void setProof(boolean proof) {
        this.proof = proof;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


