package org.jcmg.hibernate.entities;
// Generated May 22, 2015 8:17:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentTakesExamId generated by hbm2java
 */
public class StudentTakesExamId  implements java.io.Serializable {


     private int studentId;
     private int examId;
     private Date date;

    public StudentTakesExamId() {
    }

    public StudentTakesExamId(int studentId, int examId, Date date) {
       this.studentId = studentId;
       this.examId = examId;
       this.date = date;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public int getExamId() {
        return this.examId;
    }
    
    public void setExamId(int examId) {
        this.examId = examId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentTakesExamId) ) return false;
		 StudentTakesExamId castOther = ( StudentTakesExamId ) other; 
         
		 return (this.getStudentId()==castOther.getStudentId())
 && (this.getExamId()==castOther.getExamId())
 && ( (this.getDate()==castOther.getDate()) || ( this.getDate()!=null && castOther.getDate()!=null && this.getDate().equals(castOther.getDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentId();
         result = 37 * result + this.getExamId();
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );
         return result;
   }   


}


