package org.jcmg.hibernate.entities;
// Generated May 22, 2015 8:17:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int userId;
     private Company company;
     private Group group;
     private User user;
     private Set nonAttendances = new HashSet(0);
     private Set studentTakesExams = new HashSet(0);

    public Student() {
    }

	
    public Student(Company company, User user) {
        this.company = company;
        this.user = user;
    }
    public Student(Company company, Group group, User user, Set nonAttendances, Set studentTakesExams) {
       this.company = company;
       this.group = group;
       this.user = user;
       this.nonAttendances = nonAttendances;
       this.studentTakesExams = studentTakesExams;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set getNonAttendances() {
        return this.nonAttendances;
    }
    
    public void setNonAttendances(Set nonAttendances) {
        this.nonAttendances = nonAttendances;
    }
    public Set getStudentTakesExams() {
        return this.studentTakesExams;
    }
    
    public void setStudentTakesExams(Set studentTakesExams) {
        this.studentTakesExams = studentTakesExams;
    }




}


