package org.jcmg.hibernate.entities;
// Generated May 26, 2015 7:20:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private int userId;
     private User user;
     private Set groups = new HashSet(0);

    public Teacher() {
    }

    public Teacher(int userId) {
        this.userId = userId;
    }
	
    public Teacher(User user) {
        this.user = user;
    }
    public Teacher(User user, Set groups) {
       this.user = user;
       this.groups = groups;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set getGroups() {
        return this.groups;
    }
    
    public void setGroups(Set groups) {
        this.groups = groups;
    }




}


