package org.jcmg.hibernate.entities;
// Generated May 26, 2015 7:20:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String mail;
     private String firstName;
     private String lastName;
     private String phone;
     private char userType;
     private String jobPosition;
     private String pastimes;
     private String password;
     private String avatar;
     private Student student;
     private Set companies = new HashSet(0);
     private Teacher teacher;
     private Set messagesForReciever = new HashSet(0);
     private Set messagesForSender = new HashSet(0);

    public User() {
    }

    public User(String mail) {
        this.mail = mail;
    }
    
    public User(String mail, String password) {
        this.mail = mail;
        this.password = password;
    }
	
    public User(String mail, String firstName, String lastName, String phone, char userType, String password) {
        this.mail = mail;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.userType = userType;
        this.password = password;
    }
    public User(String mail, String firstName, String lastName, String phone, char userType, String jobPosition, String pastimes, String password, String avatar, Student student, Set companies, Teacher teacher, Set messagesForReciever, Set messagesForSender) {
       this.mail = mail;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phone = phone;
       this.userType = userType;
       this.jobPosition = jobPosition;
       this.pastimes = pastimes;
       this.password = password;
       this.avatar = avatar;
       this.student = student;
       this.companies = companies;
       this.teacher = teacher;
       this.messagesForReciever = messagesForReciever;
       this.messagesForSender = messagesForSender;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public char getUserType() {
        return this.userType;
    }
    
    public void setUserType(char userType) {
        this.userType = userType;
    }
    public String getJobPosition() {
        return this.jobPosition;
    }
    
    public void setJobPosition(String jobPosition) {
        this.jobPosition = jobPosition;
    }
    public String getPastimes() {
        return this.pastimes;
    }
    
    public void setPastimes(String pastimes) {
        this.pastimes = pastimes;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Set getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Set companies) {
        this.companies = companies;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public Set getMessagesForReciever() {
        return this.messagesForReciever;
    }
    
    public void setMessagesForReciever(Set messagesForReciever) {
        this.messagesForReciever = messagesForReciever;
    }
    public Set getMessagesForSender() {
        return this.messagesForSender;
    }
    
    public void setMessagesForSender(Set messagesForSender) {
        this.messagesForSender = messagesForSender;
    }




}


